import { QuestionItem, ReadingText } from './types.ts';

export const READING_TEXT_1: ReadingText = {
  id: 'reading-1',
  block: 1,
  partNumber: 6,
  titleEs: 'Texto tipo examen',
  titleHy: 'Քննության տիպի տեքստ',
  passageEs: 'Durante una clase, la profesora escribe en la pizarra:\n«El examen será el jueves a las diez.»\nLos alumnos leen la información. Después, Sergio pregunta:\n—¿Tenemos que estudiar también el tema 4?\nLa profesora responde:\n—Sí, también entra en el examen.',
  passageHy: 'Դասի ժամանակ ուսուցչուհին գրատախտակին գրում է․\n«Քննությունը կլինի հինգշաբթի ժամը տասին»։\nԱշակերտները կարդում են տեղեկությունը։ Հետո Սերխիոն հարցնում է․\n— Պե՞տք է նաև սովորենք 4-րդ թեման։\nՈւսուցչուհին պատասխանում է․\n— Այո՛, այն նույնպես մտնում է քննության մեջ։'
};

export const PRACTICE_1_QUESTIONS: QuestionItem[] = [
  // Parte 1 — Elige el elemento correcto (1-6)
  {
    id: 'p1-q1',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 1,
    scenarioEs: 'María dice a Pablo: «Mañana no hay clase».',
    scenarioHy: 'Մարիան ասում է Պաբլոյին․ «Վաղը դաս չկա»։',
    questionEs: '¿Quién es el emisor?',
    questionHy: 'Ո՞վ է հաղորդողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Pablo', textHy: 'Պաբլոն' },
      { key: 'b', textEs: 'María', textHy: 'Մարիան' },
      { key: 'c', textEs: 'La clase', textHy: 'Դասարանը' },
      { key: 'd', textEs: 'Mañana', textHy: 'Վաղը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) María',
    officialAnswerHy: 'բ) Մարիան',
    explanationEs: 'María es la persona que transmite la información a Pablo.',
    explanationHy: 'Մարիան այն անձն է, ով տեղեկությունն ուղարկում է Պաբլոյին։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p1-q2',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 2,
    scenarioEs: 'Un profesor explica una lección a sus alumnos.',
    scenarioHy: 'Ուսուցիչը դաս է բացատրում իր աշակերտներին։',
    questionEs: '¿Quiénes son los receptores?',
    questionHy: 'Ովքե՞ր են ընդունողները։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El profesor', textHy: 'Ուսուցիչը' },
      { key: 'b', textEs: 'Los alumnos', textHy: 'Աշակերտները' },
      { key: 'c', textEs: 'La lección', textHy: 'Դասը' },
      { key: 'd', textEs: 'El aula', textHy: 'Դասասենյակը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Los alumnos',
    officialAnswerHy: 'բ) Աշակերտները',
    explanationEs: 'Los alumnos son quienes reciben y escuchan la explicación del profesor.',
    explanationHy: 'Աշակերտներն են նրանք, ովքեր լսում և ստանում են ուսուցչի բացատրությունը։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p1-q3',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 3,
    scenarioEs: 'Ana escribe: «Llegaré a las cinco».',
    scenarioHy: 'Անան գրում է․ «Կհասնեմ ժամը հինգին»։',
    questionEs: '¿Cuál es el mensaje?',
    questionHy: 'Ո՞րն է հաղորդագրությունը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Ana', textHy: 'Անան' },
      { key: 'b', textEs: 'El teléfono', textHy: 'Հեռախոսը' },
      { key: 'c', textEs: '«Llegaré a las cinco»', textHy: '«Կհասնեմ ժամը հինգին»' },
      { key: 'd', textEs: 'El español', textHy: 'Իսպաներենը' }
    ],
    correctKey: 'c',
    officialAnswerEs: 'c) «Llegaré a las cinco»',
    officialAnswerHy: 'գ) «Կհասնեմ ժամը հինգին»',
    explanationEs: 'El mensaje es la información concreta comunicada por Ana.',
    explanationHy: 'Հաղորդագրությունը հենց այն կոնկրետ տեղեկությունն է, ինչ Անան հայտնում է։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p1-q4',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 4,
    scenarioEs: 'Dos amigos hablan por teléfono.',
    scenarioHy: 'Երկու ընկեր խոսում են հեռախոսով։',
    questionEs: '¿Cuál es el canal?',
    questionHy: 'Ո՞րն է հաղորդման միջոցը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'b', textEs: 'El teléfono', textHy: 'Հեռախոսը' },
      { key: 'c', textEs: 'Los amigos', textHy: 'Ընկերները' },
      { key: 'd', textEs: 'La conversación', textHy: 'Զրույցը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) El teléfono',
    officialAnswerHy: 'բ) Հեռախոսը',
    explanationEs: 'El teléfono es el medio físico/tecnológico a través del cual viaja la señal.',
    explanationHy: 'Հեռախոսը այն ֆիզիկական/տեխնիկական միջոցն է, որի միջոցով ձայնը փոխանցվում է։',
    highlightCategory: 'canal'
  },
  {
    id: 'p1-q5',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 5,
    scenarioEs: 'Dos alumnos españoles hablan en español.',
    scenarioHy: 'Երկու իսպանացի աշակերտ խոսում են իսպաներեն։',
    questionEs: '¿Cuál es el código?',
    questionHy: 'Ո՞րն է կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'b', textEs: 'El aula', textHy: 'Դասարանը' },
      { key: 'c', textEs: 'La voz', textHy: 'Ձայնը' },
      { key: 'd', textEs: 'Los alumnos', textHy: 'Աշակերտները' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) El español',
    officialAnswerHy: 'ա) Իսպաներենը',
    explanationEs: 'El código es el idioma (sistema de signos y reglas) utilizado para comunicarse.',
    explanationHy: 'Կոդը լեզուն է (նշանների և կանոնների համակարգը), որով հաղորդակցվում են։',
    highlightCategory: 'código'
  },
  {
    id: 'p1-q6',
    block: 1,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige el elemento correcto',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարրը',
    number: 6,
    scenarioEs: 'Un entrenador habla con sus jugadores durante un partido.',
    scenarioHy: 'Մարզիչը խոսում է իր խաղացողների հետ հանդիպման ժամանակ։',
    questionEs: '¿Cuál es el contexto o situación?',
    questionHy: 'Ո՞րն է իրավիճակը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El entrenador', textHy: 'Մարզիչը' },
      { key: 'b', textEs: 'Los jugadores', textHy: 'Խաղացողները' },
      { key: 'c', textEs: 'Un partido de fútbol', textHy: 'Ֆուտբոլային հանդիպումը' },
      { key: 'd', textEs: 'El español', textHy: 'Իսպաներենը' }
    ],
    correctKey: 'c',
    officialAnswerEs: 'c) Un partido de fútbol',
    officialAnswerHy: 'գ) Ֆուտբոլային հանդիպումը',
    explanationEs: 'El contexto son las circunstancias y el lugar donde se produce la comunicación.',
    explanationHy: 'Համատեքստը հաղորդակցության տեղի ունենալու իրավիճակն ու հանգամանքներն են։',
    highlightCategory: 'contexto'
  },

  // Parte 2 — Situaciones prácticas (7-10)
  {
    id: 'p1-q7',
    block: 1,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Situaciones prácticas',
    partTitleHy: 'Մաս 2 — Գործնական իրավիճակներ',
    number: 7,
    scenarioEs: 'Una madre manda a su hijo un mensaje: «Compra pan cuando vuelvas a casa.»',
    scenarioHy: 'Մայրը որդուն հաղորդագրություն է ուղարկում․ «Տուն վերադառնալիս հաց գնիր»։',
    questionEs: 'Identifica los seis elementos de la comunicación.',
    questionHy: 'Որոշի՛ր հաղորդակցության բոլոր 6 տարրերը։',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'la madre', answerHy: 'մայրը' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'el hijo', answerHy: 'որդին' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Compra pan cuando vuelvas a casa.»', answerHy: '«Տուն վերադառնալիս հաց գնիր»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'teléfono / mensaje escrito', answerHy: 'հեռախոս / գրավոր հաղորդագրություն' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'comunicación entre una madre y su hijo / encargo familiar', answerHy: 'մայրն ինչ-որ բան է խնդրում որդուց' }
    ],
    officialAnswerEs: 'Emisor: la madre | Receptor: el hijo | Mensaje: «Compra pan cuando vuelvas a casa.» | Canal: teléfono / mensaje escrito | Código: español | Contexto: comunicación entre una madre y su hijo',
    officialAnswerHy: 'Հաղորդող՝ մայրը | Ընդունող՝ որդին | Հաղորդագրություն՝ «Տուն վերադառնալիս հաց գնիր» | Միջոց՝ հեռախոս | Կոդ՝ իսպաներեն | Իրավիճակ՝ մայրն ինչ-որ բան է խնդրում որդուց',
    highlightCategory: 'general'
  },
  {
    id: 'p1-q8',
    block: 1,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Situaciones prácticas',
    partTitleHy: 'Մաս 2 — Գործնական իրավիճակներ',
    number: 8,
    scenarioEs: 'El profesor dice en clase: «Mañana tenemos examen de Lengua.»',
    scenarioHy: 'Ուսուցիչը դասարանում ասում է․ «Վաղը իսպաներենի քննություն ունենք»։',
    questionEs: 'Completa los elementos de la comunicación.',
    questionHy: 'Լրացրո՛ւ հաղորդակցության տարրերը։',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'el profesor', answerHy: 'ուսուցիչը' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'los alumnos', answerHy: 'աշակերտները' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: 'Mañana tenemos examen de Lengua', answerHy: 'Վաղը իսպաներենի քննություն ունենք' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'la voz / canal oral (el aire)', answerHy: 'ձայնը / բանավոր միջոց' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'una clase de Lengua en el instituto', answerHy: 'դասարանը / դասը' }
    ],
    officialAnswerEs: 'Emisor: el profesor | Receptor: los alumnos | Mensaje: Mañana tenemos examen de Lengua | Canal: la voz / canal oral | Código: español | Contexto: una clase',
    officialAnswerHy: 'Հաղորդող՝ ուսուցիչը | Ընդունող՝ աշակերտները | Հաղորդագրություն՝ Վաղը քննություն ունենք | Միջոց՝ ձայնը | Կոդ՝ իսպաներեն | Իրավիճակ՝ դասը',
    highlightCategory: 'general'
  },
  {
    id: 'p1-q9',
    block: 1,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Situaciones prácticas',
    partTitleHy: 'Մաս 2 — Գործնական իրավիճակներ',
    number: 9,
    scenarioEs: 'Un jugador ve una señal que dice: «Prohibido entrar al campo.»',
    scenarioHy: 'Խաղացողը տեսնում է ցուցանակ, որի վրա գրված է․ «Դաշտ մուտքն արգելված է»։',
    questionEs: '¿Quién es el receptor?',
    questionHy: 'Ո՞վ է ընդունողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'La señal', textHy: 'Ցուցանակը' },
      { key: 'b', textEs: 'Las personas que leen la señal', textHy: 'Ցուցանակը կարդացող մարդիկ' },
      { key: 'c', textEs: 'El campo', textHy: 'Դաշտը' },
      { key: 'd', textEs: 'La palabra «prohibido»', textHy: '«Արգելված է» բառը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Las personas que leen la señal',
    officialAnswerHy: 'բ) Այն մարդիկ, ովքեր կարդում են ցուցանակը։',
    explanationEs: 'El receptor es quien descodifica y lee el mensaje visual escrito.',
    explanationHy: 'Ընդունողը այն մարդն է, ով տեսնում և կարդում է գրված հաղորդագրությունը։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p1-q10',
    block: 1,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Situaciones prácticas',
    partTitleHy: 'Մաս 2 — Գործնական իրավիճակներ',
    number: 10,
    scenarioEs: 'En esa misma situación («Prohibido entrar al campo.»):',
    scenarioHy: 'Նույն այդ իրավիճակում («Դաշտ մուտքն արգելված է»)․',
    questionEs: '¿Cuál es el canal?',
    questionHy: 'Ո՞րն է հաղորդման միջոցը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El cartel', textHy: 'Ցուցանակը / պաստառը' },
      { key: 'b', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'c', textEs: 'El jugador', textHy: 'Խաղացողը' },
      { key: 'd', textEs: 'La prohibición', textHy: 'Արգելքը' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) El cartel',
    officialAnswerHy: 'ա) Ցուցանակը (պաստառը)',
    explanationEs: 'El cartel (soporte físico / canal escrito) es por donde se transmite el mensaje.',
    explanationHy: 'Ցուցանակը այն ֆիզիկական հիմքն է (կրիչը), որի վրա գրված է հաղորդագրությունը։',
    highlightCategory: 'canal'
  },

  // Parte 3 — Diferencia entre canal y código (11-12 + Recuerda)
  {
    id: 'p1-q11',
    block: 1,
    partNumber: 3,
    partTitleEs: 'Parte 3 — Diferencia entre canal y código',
    partTitleHy: 'Մաս 3 — Canal և código տարբերությունը',
    number: 11,
    scenarioEs: 'Dos personas hablan en español por videollamada.',
    scenarioHy: 'Երկու հոգի խոսում են իսպաներեն տեսազանգով։',
    questionEs: '¿Qué es el código?',
    questionHy: 'Ի՞նչն է կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'La videollamada', textHy: 'Տեսազանգը' },
      { key: 'b', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'c', textEs: 'Las personas', textHy: 'Մարդիկ' },
      { key: 'd', textEs: 'La cámara', textHy: 'Տեսախցիկը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) El español',
    officialAnswerHy: 'բ) Իսպաներենը',
    explanationEs: 'Código = lengua o sistema de signos (Կոդ = լեզու կամ նշանների համակարգ)։',
    explanationHy: 'Կոդը այն լեզուն է, որով նրանք խոսում են (իսպաներեն)։',
    highlightCategory: 'código'
  },
  {
    id: 'p1-q12',
    block: 1,
    partNumber: 3,
    partTitleEs: 'Parte 3 — Diferencia entre canal y código',
    partTitleHy: 'Մաս 3 — Canal և código տարբերությունը',
    number: 12,
    scenarioEs: 'En la misma situación (hablan en español por videollamada):',
    scenarioHy: 'Նույն իրավիճակում (խոսում են իսպաներեն տեսազանգով)․',
    questionEs: '¿Qué es el canal?',
    questionHy: 'Ի՞նչն է հաղորդման ալիքը / միջոցը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'b', textEs: 'La videollamada', textHy: 'Տեսազանգը' },
      { key: 'c', textEs: 'El mensaje', textHy: 'Հաղորդագրությունը' },
      { key: 'd', textEs: 'El receptor', textHy: 'Ընդունողը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) La videollamada',
    officialAnswerHy: 'բ) Տեսազանգը',
    explanationEs: 'Canal = medio físico/digital por el que llega el mensaje (Ալիք = միջոց, որով հաղորդագրությունը հասնում է)։',
    explanationHy: 'Տեսազանգը այն տեխնիկական միջոցն է, որի միջոցով հաղորդակցությունը տեղի է ունենում։',
    highlightCategory: 'canal'
  },

  // Parte 4 — ¿Quién es quién? (13-16)
  {
    id: 'p1-q13',
    block: 1,
    partNumber: 4,
    partTitleEs: 'Parte 4 — ¿Quién es quién?',
    partTitleHy: 'Մաս 4 — Ո՞վ ով է',
    number: 13,
    scenarioEs: 'Laura escribe un correo electrónico a su profesora para preguntar por los deberes.',
    scenarioHy: 'Լաուրան էլեկտրոնային նամակ է գրում իր ուսուցչուհուն տնային առաջադրանքների մասին հարցնելու համար։',
    questionEs: '¿Quién es el emisor?',
    questionHy: 'Ո՞վ է հաղորդողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Laura', textHy: 'Լաուրան' },
      { key: 'b', textEs: 'La profesora', textHy: 'Ուսուցչուհին' },
      { key: 'c', textEs: 'El correo', textHy: 'Էլ․ փոստը' },
      { key: 'd', textEs: 'Los deberes', textHy: 'Տնայինները' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Laura',
    officialAnswerHy: 'ա) Լաուրան',
    explanationEs: 'Laura escribe el mensaje, por lo tanto es quien lo emite.',
    explanationHy: 'Լաուրան է գրում նամակը, ուստի նա հաղորդողն է։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p1-q14',
    block: 1,
    partNumber: 4,
    partTitleEs: 'Parte 4 — ¿Quién es quién?',
    partTitleHy: 'Մաս 4 — Ո՞վ ով է',
    number: 14,
    scenarioEs: 'Laura escribe un correo electrónico a su profesora para preguntar por los deberes.',
    scenarioHy: 'Լաուրան էլեկտրոնային նամակ է գրում իր ուսուցչուհուն տնայինների մասին։',
    questionEs: '¿Quién es el receptor?',
    questionHy: 'Ո՞վ է ընդունողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Laura', textHy: 'Լաուրան' },
      { key: 'b', textEs: 'La profesora', textHy: 'Ուսուցչուհին' },
      { key: 'c', textEs: 'El ordenador', textHy: 'Համակարգիչը' },
      { key: 'd', textEs: 'El correo', textHy: 'Էլ․ նամակը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) La profesora',
    officialAnswerHy: 'բ) Ուսուցչուհին',
    explanationEs: 'La profesora es a quien va dirigido el correo y quien lo va a leer.',
    explanationHy: 'Ուսուցչուհին նամակը ստացողն ու կարդացողն է։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p1-q15',
    block: 1,
    partNumber: 4,
    partTitleEs: 'Parte 4 — ¿Quién es quién?',
    partTitleHy: 'Մաս 4 — Ո՞վ ով է',
    number: 15,
    scenarioEs: 'Laura escribe un correo electrónico a su profesora para preguntar por los deberes.',
    scenarioHy: 'Լաուրան էլեկտրոնային նամակ է գրում իր ուսուցչուհուն։',
    questionEs: '¿Cuál es el canal?',
    questionHy: 'Ո՞րն է հաղորդման միջոցը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Español', textHy: 'Իսպաներեն' },
      { key: 'b', textEs: 'Correo electrónico', textHy: 'Էլեկտրոնային փոստը' },
      { key: 'c', textEs: 'Profesora', textHy: 'Ուսուցչուհին' },
      { key: 'd', textEs: 'Deberes', textHy: 'Տնայինները' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Correo electrónico',
    officialAnswerHy: 'բ) Էլեկտրոնային փոստը',
    explanationEs: 'El correo electrónico (internet / soporte digital) es el canal.',
    explanationHy: 'Էլեկտրոնային փոստը այն թվային միջոցն է, որով նամակը հասնում է։',
    highlightCategory: 'canal'
  },
  {
    id: 'p1-q16',
    block: 1,
    partNumber: 4,
    partTitleEs: 'Parte 4 — ¿Quién es quién?',
    partTitleHy: 'Մաս 4 — Ո՞վ ով է',
    number: 16,
    scenarioEs: 'Laura escribe un correo electrónico a su profesora para preguntar por los deberes.',
    scenarioHy: 'Լաուրան էլ․ նամակ է գրում ուսուցչուհուն։',
    questionEs: '¿Cuál es el código?',
    questionHy: 'Ո՞րն է կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Español', textHy: 'Իսպաներեն' },
      { key: 'b', textEs: 'Internet', textHy: 'Ինտերնետ' },
      { key: 'c', textEs: 'Laura', textHy: 'Լաուրա' },
      { key: 'd', textEs: 'Profesora', textHy: 'Ուսուցչուհի' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Español',
    officialAnswerHy: 'ա) Իսպաներեն',
    explanationEs: 'El código es la lengua española con la que está redactado el texto.',
    explanationHy: 'Կոդը իսպաներեն լեզուն է, որով շարադրված է տեքստը։',
    highlightCategory: 'código'
  },

  // Parte 5 — Encuentra el error (17-18)
  {
    id: 'p1-q17',
    block: 1,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Encuentra el error',
    partTitleHy: 'Մաս 5 — Գտի՛ր սխալը',
    number: 17,
    scenarioEs: 'Situación: Pedro habla con Ana por teléfono en español.\nUn alumno responde:\nEmisor: Pedro\nReceptor: Ana\nCanal: español\nCódigo: teléfono',
    scenarioHy: 'Իրավիճակ․ Պեդրոն Անայի հետ հեռախոսով խոսում է իսպաներեն։\nԱշակերտը պատասխանում է․\nՀաղորդող՝ Պեդրո\nԸնդունող՝ Անա\nՄիջոց՝ իսպաներեն\nԿոդ՝ հեռախոս',
    questionEs: '¿Qué está mal? ¿Cómo debe ser correctamente?',
    questionHy: 'Ի՞նչն է սխալ։ Ինչպե՞ս պետք է լինի ճիշտ տարբերակը։',
    type: 'error_detection',
    officialAnswerEs: 'Están intercambiados canal y código. Correcto: Canal: teléfono | Código: español.',
    officialAnswerHy: 'Ալիքն ու կոդը փոխված են տեղերով։ Ճիշտ է՝ Միջոց/ալիք՝ հեռախոս | Կոդ՝ իսպաներեն։',
    explanationEs: 'El teléfono es el medio físico (canal), y el español es el idioma (código).',
    explanationHy: 'Հեռախոսը ֆիզիկական հաղորդման միջոցն է (canal), իսկ իսպաներենը լեզուն է (código)։',
    highlightCategory: 'canal'
  },
  {
    id: 'p1-q18',
    block: 1,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Encuentra el error',
    partTitleHy: 'Մաս 5 — Գտի՛ր սխալը',
    number: 18,
    scenarioEs: 'El profesor escribe en la pizarra: «El examen es el viernes.»\nUn alumno dice: Mensaje: la pizarra.',
    scenarioHy: 'Ուսուցիչը գրատախտակին գրում է․ «Քննությունը ուրբաթ օրն է»։\nԱշակերտն ասում է․ Հաղորդագրությունը գրատախտակն է։',
    questionEs: '¿Es correcto? Explica por qué.',
    questionHy: 'Ճի՞շտ է արդյոք։ Բացատրի՛ր ինչու։',
    type: 'error_detection',
    officialAnswerEs: 'No. La pizarra es parte del canal. El mensaje es: «El examen es el viernes.»',
    officialAnswerHy: 'Ոչ։ Գրատախտակը հաղորդման միջոցն է (կրիչը), իսկ հաղորդագրությունը հենց գրված նախադասությունն է՝ «Քննությունը ուրբաթ օրն է»։',
    explanationEs: 'El canal es el soporte material (la pizarra), mientras que el mensaje es el contenido lingüístico transmitido.',
    explanationHy: 'Գրատախտակը ֆիզիկական կրիչն է, իսկ հաղորդագրությունը՝ բուն տեղեկությունը։',
    highlightCategory: 'mensaje'
  },

  // Parte 6 — Texto tipo examen (19-24)
  {
    id: 'p1-q19',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 19,
    scenarioEs: 'Texto: La profesora escribe en la pizarra «El examen será el jueves a las diez.» Los alumnos leen...',
    scenarioHy: 'Տեքստ․ Ուսուցչուհին գրատախտակին գրում է «Քննությունը կլինի հինգշաբթի ժամը տասին»։ Աշակերտները կարդում են...',
    questionEs: '¿Quién es el emisor del primer mensaje?',
    questionHy: 'Ո՞վ է առաջին հաղորդագրության հաղորդողը։',
    type: 'open',
    officialAnswerEs: 'La profesora.',
    officialAnswerHy: 'Ուսուցչուհին։',
    explanationEs: 'La profesora es quien redacta y escribe el mensaje en la pizarra.',
    explanationHy: 'Ուսուցչուհին է առաջին հաղորդագրությունը գրողը։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p1-q20',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 20,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Quiénes son los receptores?',
    questionHy: 'Ովքե՞ր են ընդունողները։',
    type: 'open',
    officialAnswerEs: 'Los alumnos.',
    officialAnswerHy: 'Աշակերտները։',
    explanationEs: 'Los alumnos presentes en clase leen e interpretan el mensaje.',
    explanationHy: 'Դասարանում գտնվող աշակերտներն են կարդում գրվածը։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p1-q21',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 21,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el mensaje?',
    questionHy: 'Ո՞րն է հաղորդագրությունը։',
    type: 'open',
    officialAnswerEs: '«El examen será el jueves a las diez.»',
    officialAnswerHy: '«Քննությունը կլինի հինգշաբթի ժամը տասին»։',
    explanationEs: 'El mensaje es el texto exacto que comunica la fecha y hora del examen.',
    explanationHy: 'Հաղորդագրությունը հենց քննության օրվա և ժամի մասին տեղեկությունն է։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p1-q22',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 22,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el código?',
    questionHy: 'Ո՞րն է կոդը։',
    type: 'open',
    officialAnswerEs: 'El español.',
    officialAnswerHy: 'Իսպաներենը։',
    explanationEs: 'El idioma castellano/español es el sistema de signos empleado.',
    explanationHy: 'Օգտագործված նշանների համակարգը իսպաներենն է։',
    highlightCategory: 'código'
  },
  {
    id: 'p1-q23',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 23,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el canal principal del primer mensaje?',
    questionHy: 'Ո՞րն է առաջին հաղորդագրության հիմնական միջոցը։',
    type: 'open',
    officialAnswerEs: 'La pizarra / canal escrito.',
    officialAnswerHy: 'Գրատախտակը / գրավոր միջոցը։',
    explanationEs: 'La pizarra sirve como soporte físico visual para el texto escrito.',
    explanationHy: 'Գրատախտակը ծառայում է որպես գրավոր տեքստի ֆիզիկական կրիչ։',
    highlightCategory: 'canal'
  },
  {
    id: 'p1-q24',
    block: 1,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto tipo examen',
    partTitleHy: 'Մաս 6 — Քննության տիպի տեքստ',
    number: 24,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el contexto?',
    questionHy: 'Ո՞րն է համատեքստը / իրավիճակը։',
    type: 'open',
    officialAnswerEs: 'Una clase, antes de un examen.',
    officialAnswerHy: 'Դասարանը / դասը՝ քննության նախապատրաստվելիս։',
    explanationEs: 'El marco escolar y la proximidad del examen definen el contexto.',
    explanationHy: 'Դպրոցական դասը և առաջիկա քննությունը ստեղծում են հաղորդակցական իրավիճակը։',
    highlightCategory: 'contexto'
  },

  // Parte 7 — Sin opciones (25-26)
  {
    id: 'p1-q25',
    block: 1,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Sin opciones',
    partTitleHy: 'Մաս 7 — Առանց տարբերակների',
    number: 25,
    scenarioEs: 'Un entrenador grita durante un partido: «¡Defended mejor!»',
    scenarioHy: 'Մարզիչը գոռում է խաղի ժամանակ․ «Ավելի լավ պաշտպանվե՛ք»։',
    questionEs: 'Completa los seis elementos por ti mismo.',
    questionHy: 'Ինքնուրույն լրացրո՛ւ բոլոր 6 տարրերը։',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'el entrenador', answerHy: 'մարզիչը' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'los jugadores', answerHy: 'խաղացողները' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«¡Defended mejor!»', answerHy: '«Ավելի լավ պաշտպանվե՛ք»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'la voz / canal oral (el aire)', answerHy: 'ձայնը / բանավոր միջոց (օդը)' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'un partido de fútbol', answerHy: 'ֆուտբոլային հանդիպում' }
    ],
    officialAnswerEs: 'Emisor: el entrenador | Receptor: los jugadores | Mensaje: «¡Defended mejor!» | Canal: la voz / canal oral | Código: español | Contexto: un partido de fútbol',
    officialAnswerHy: 'Հաղորդող՝ մարզիչը | Ընդունող՝ խաղացողները | Հաղորդագրություն՝ «Ավելի լավ պաշտպանվե՛ք» | Միջոց՝ ձայնը | Կոդ՝ իսպաներեն | Իրավիճակ՝ ֆուտբոլի խաղը',
    highlightCategory: 'general'
  },
  {
    id: 'p1-q26',
    block: 1,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Sin opciones',
    partTitleHy: 'Մաս 7 — Առանց տարբերակների',
    number: 26,
    scenarioEs: 'Marta manda a Elena un mensaje de WhatsApp: «Nos vemos a las seis delante del cine.»',
    scenarioHy: 'Մարթան Էլենային WhatsApp-ով հաղորդագրություն է գրում․ «Կհանդիպենք վեցին կինոթատրոնի դիմաց»։',
    questionEs: 'Completa los seis elementos de la comunicación.',
    questionHy: 'Լրացրո՛ւ հաղորդակցության բոլոր վեց տարրերը։',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'Marta', answerHy: 'Մարթան' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'Elena', answerHy: 'Էլենան' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Nos vemos a las seis delante del cine.»', answerHy: '«Կհանդիպենք վեցին կինոթատրոնի դիմաց»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'WhatsApp / teléfono móvil (canal digital)', answerHy: 'WhatsApp / հեռախոս (թվային միջոց)' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'dos amigas organizando un encuentro', answerHy: 'երկու ընկերուհի պայմանավորվում են հանդիպման մասին' }
    ],
    officialAnswerEs: 'Emisor: Marta | Receptor: Elena | Mensaje: Nos vemos a las seis delante del cine | Canal: WhatsApp / teléfono | Código: español | Contexto: dos amigas organizando un encuentro',
    officialAnswerHy: 'Հաղորդող՝ Մարթա | Ընդունող՝ Էլենա | Հաղորդագրություն՝ Կհանդիպենք վեցին կինոյի մոտ | Միջոց՝ WhatsApp | Կոդ՝ իսպաներեն | Իրավիճակ՝ երկու ընկերուհիների պայմանավորվելը',
    highlightCategory: 'general'
  },

  // Parte 8 — Preguntas con trampa (27-30)
  {
    id: 'p1-q27',
    block: 1,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Preguntas con trampa',
    partTitleHy: 'Մաս 8 — Խորամանկ հարցեր',
    number: 27,
    scenarioEs: 'Si una persona habla por teléfono en español...',
    scenarioHy: 'Եթե մարդը հեռախոսով խոսում է իսպաներեն․․․',
    questionEs: '¿Qué es el español?',
    questionHy: 'Ի՞նչն է իսպաներենը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Canal', textHy: 'Ալիք / միջոց' },
      { key: 'b', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'c', textEs: 'Mensaje', textHy: 'Հաղորդագրություն' },
      { key: 'd', textEs: 'Contexto', textHy: 'Համատեքստ' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Código',
    officialAnswerHy: 'բ) Կոդ',
    explanationEs: 'La lengua hablada o escrita es siempre el código.',
    explanationHy: 'Լեզուն, որով խոսում կամ գրում են, միշտ կոդն է։',
    highlightCategory: 'código'
  },
  {
    id: 'p1-q28',
    block: 1,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Preguntas con trampa',
    partTitleHy: 'Մաս 8 — Խորամանկ հարցեր',
    number: 28,
    scenarioEs: 'En la misma situación (hablan por teléfono en español):',
    scenarioHy: 'Նույն իրավիճակում (հեռախոսով խոսում են իսպաներեն)․',
    questionEs: '¿Y qué es el teléfono?',
    questionHy: 'Իսկ ի՞նչ է հեռախոսը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'b', textEs: 'Emisor', textHy: 'Հաղորդող' },
      { key: 'c', textEs: 'Canal', textHy: 'Ալիք / միջոց' },
      { key: 'd', textEs: 'Mensaje', textHy: 'Հաղորդագրություն' }
    ],
    correctKey: 'c',
    officialAnswerEs: 'c) Canal',
    officialAnswerHy: 'գ) Ալիք / հաղորդման միջոց',
    explanationEs: 'El dispositivo telefónico es el canal físico.',
    explanationHy: 'Հեռախոս սարքը ֆիզիկական հաղորդման միջոցն է (ալիքը)։',
    highlightCategory: 'canal'
  },
  {
    id: 'p1-q29',
    block: 1,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Preguntas con trampa',
    partTitleHy: 'Մաս 8 — Խորամանկ հարցեր',
    number: 29,
    scenarioEs: 'En un diálogo o conversación:',
    scenarioHy: 'Երկխոսության կամ զրույցի ընթացքում․',
    questionEs: 'Si el receptor responde, ¿puede convertirse en emisor?',
    questionHy: 'Եթե ընդունողը պատասխանում է, կարո՞ղ է նա դառնալ հաղորդող։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Sí', textHy: 'Այո' },
      { key: 'b', textEs: 'No', textHy: 'Ոչ' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Sí',
    officialAnswerHy: 'ա) Այո',
    explanationEs: 'En una conversación, los participantes cambian continuamente de papel (feedback o retroalimentación).',
    explanationHy: 'Զրույցի ընթացքում մասնակիցները անընդհատ փոխում են իրենց դերերը (հաղորդողը դառնում է ընդունող և հակառակը)։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p1-q30',
    block: 1,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Preguntas con trampa',
    partTitleHy: 'Մաս 8 — Խորամանկ հարցեր',
    number: 30,
    scenarioEs: 'Entre dos hablantes:',
    scenarioHy: 'Երկու խոսողների միջև․',
    questionEs: '¿Puede haber comunicación si el receptor no entiende el código?',
    questionHy: 'Կարո՞ղ է արդյոք հաղորդակցություն լինել, եթե ընդունողը չի հասկանում կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Sí, siempre', textHy: 'Այո, միշտ' },
      { key: 'b', textEs: 'No de forma efectiva', textHy: 'Ոչ արդյունավետ կերպով' },
      { key: 'c', textEs: 'El código no importa', textHy: 'Կոդը նշանակություն չունի' },
      { key: 'd', textEs: 'Solo depende del canal', textHy: 'Կախված է միայն ալիքից' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) No de forma efectiva',
    officialAnswerHy: 'բ) Ոչ արդյունավետ կերպով',
    explanationEs: 'Si el receptor no domina el código, no puede descodificar el mensaje.',
    explanationHy: 'Եթե ընդունողը չի հասկանում կոդը (օր․՝ օտար լեզու), հաղորդագրությունը չի ընկալվի։',
    highlightCategory: 'código'
  }
];
