import { QuestionItem, ReadingText } from './types.ts';

export const READING_TEXT_2: ReadingText = {
  id: 'reading-2',
  block: 2,
  partNumber: 6,
  titleEs: 'Texto para analizar',
  titleHy: 'Վերլուծի՛ր տեքստը',
  passageEs: 'Al terminar la clase, el profesor dice:\n—Mañana traeréis el libro de Ciencias.\nDespués escribe la misma información en la pizarra.\nCarlos pregunta:\n—¿También tenemos que traer el cuaderno?\nEl profesor responde:\n—Sí.',
  passageHy: 'Դասի վերջում ուսուցիչն ասում է․\n— Վաղը բերելու եք բնագիտության գիրքը։\nՀետո նույն տեղեկությունը գրում է գրատախտակին։\nԿառլոսը հարցնում է․\n— Տետրը նույնպես պե՞տք է բերենք։\nՈւսուցիչը պատասխանում է․\n— Այո՛։'
};

export const PRACTICE_2_QUESTIONS: QuestionItem[] = [
  // Parte 1 — Elige la respuesta correcta (1-5)
  {
    id: 'p2-q1',
    block: 2,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    number: 1,
    scenarioEs: 'Pablo envía a su amigo: «Llegaré diez minutos tarde».',
    scenarioHy: 'Պաբլոն ընկերոջն ուղարկում է․ «Տասը րոպե ուշ կհասնեմ»։',
    questionEs: '¿Quién es el emisor?',
    questionHy: 'Ո՞վ է հաղորդողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El amigo', textHy: 'Ընկերը' },
      { key: 'b', textEs: 'Pablo', textHy: 'Պաբլոն' },
      { key: 'c', textEs: 'El móvil', textHy: 'Բջջայինը' },
      { key: 'd', textEs: 'El mensaje', textHy: 'Հաղորդագրությունը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Pablo',
    officialAnswerHy: 'բ) Պաբլոն',
    explanationEs: 'Pablo es quien redacta y manda el mensaje.',
    explanationHy: 'Պաբլոն է հաղորդագրությունը կազմողն ու ուղարկողը։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p2-q2',
    block: 2,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    number: 2,
    scenarioEs: 'Una profesora escribe en la pizarra: «Página 42».',
    scenarioHy: 'Ուսուցչուհին գրատախտակին գրում է․ «Էջ 42»։',
    questionEs: '¿Cuál es el mensaje?',
    questionHy: 'Ո՞րն է հաղորդագրությունը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'La profesora', textHy: 'Ուսուցչուհին' },
      { key: 'b', textEs: 'La pizarra', textHy: 'Գրատախտակը' },
      { key: 'c', textEs: '«Página 42»', textHy: '«Էջ 42»' },
      { key: 'd', textEs: 'La clase', textHy: 'Դասարանը' }
    ],
    correctKey: 'c',
    officialAnswerEs: 'c) «Página 42»',
    officialAnswerHy: 'գ) «Էջ 42»',
    explanationEs: 'El contenido informativo escrito es «Página 42».',
    explanationHy: 'Գրված բուն տեղեկությունը «Էջ 42»-ն է։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p2-q3',
    block: 2,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    number: 3,
    scenarioEs: 'Dos personas hablan en armenio.',
    scenarioHy: 'Երկու մարդ խոսում են հայերեն։',
    questionEs: '¿Cuál es el código?',
    questionHy: 'Ո՞րն է կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'La voz', textHy: 'Ձայնը' },
      { key: 'b', textEs: 'El armenio', textHy: 'Հայերենը' },
      { key: 'c', textEs: 'Las personas', textHy: 'Մարդիկ' },
      { key: 'd', textEs: 'El lugar', textHy: 'Վայրը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) El armenio',
    officialAnswerHy: 'բ) Հայերենը',
    explanationEs: 'El idioma armenio es el sistema de signos empleado.',
    explanationHy: 'Հայերեն լեզուն օգտագործվող նշանների համակարգն է (կոդը)։',
    highlightCategory: 'código'
  },
  {
    id: 'p2-q4',
    block: 2,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    number: 4,
    scenarioEs: 'Un alumno escucha un mensaje por los altavoces del colegio.',
    scenarioHy: 'Աշակերտը դպրոցի բարձրախոսներով հաղորդագրություն է լսում։',
    questionEs: '¿Cuál es el canal?',
    questionHy: 'Ո՞րն է հաղորդման ալիքը / միջոցը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'b', textEs: 'Los altavoces', textHy: 'Բարձրախոսները' },
      { key: 'c', textEs: 'El alumno', textHy: 'Աշակերտը' },
      { key: 'd', textEs: 'El mensaje', textHy: 'Հաղորդագրությունը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Los altavoces',
    officialAnswerHy: 'բ) Բարձրախոսները',
    explanationEs: 'Los altavoces y las ondas sonoras forman el canal físico de transmisión.',
    explanationHy: 'Բարձրախոսները այն ֆիզիկական սարքերն ու միջոցն են, որոնցով տարածվում է ձայնը։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q5',
    block: 2,
    partNumber: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    number: 5,
    scenarioEs: 'En una biblioteca, una bibliotecaria dice: «Por favor, guardad silencio».',
    scenarioHy: 'Գրադարանում գրադարանավարուհին ասում է․ «Խնդրում եմ, լռություն պահպանեք»։',
    questionEs: '¿Cuál es el contexto?',
    questionHy: 'Ո՞րն է իրավիճակը / համատեքստը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Una biblioteca', textHy: 'Գրադարանը' },
      { key: 'b', textEs: 'El español', textHy: 'Իսպաներենը' },
      { key: 'c', textEs: 'La bibliotecaria', textHy: 'Գրադարանավարուհին' },
      { key: 'd', textEs: 'El silencio', textHy: 'Լռությունը' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Una biblioteca',
    officialAnswerHy: 'ա) Գրադարանը',
    explanationEs: 'El lugar y las normas de la biblioteca configuran la situación comunicativa.',
    explanationHy: 'Գրադարանի միջավայրն ու կանոնները ստեղծում են հաղորդակցական իրավիճակը։',
    highlightCategory: 'contexto'
  },

  // Parte 2 — Completa los elementos (6-8)
  {
    id: 'p2-q6',
    block: 2,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Completa los elementos',
    partTitleHy: 'Մաս 2 — Լրացրո՛ւ տարրերը',
    number: 6,
    scenarioEs: 'Un médico dice a un paciente: «Tome esta medicina después de comer.»',
    scenarioHy: 'Բժիշկն ասում է պացիենտին․ «Այս դեղը խմեք ուտելուց հետո»։',
    questionEs: 'Completa los seis elementos:',
    questionHy: 'Լրացրո՛ւ վեց տարրերը․',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'el médico', answerHy: 'բժիշկը' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'el paciente', answerHy: 'պացիենտը' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Tome esta medicina después de comer»', answerHy: '«Այս դեղը խմեք ուտելուց հետո»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'la voz / canal oral', answerHy: 'ձայնը / բանավոր միջոց' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'consulta médica', answerHy: 'բժշկական ընդունելություն' }
    ],
    officialAnswerEs: 'Emisor: el médico | Receptor: el paciente | Mensaje: Tome esta medicina después de comer | Canal: la voz / canal oral | Código: español | Contexto: consulta médica',
    officialAnswerHy: 'Հաղորդող՝ բժիշկը | Ընդունող՝ պացիենտը | Հաղորդագրություն՝ Դեղը խմեք ուտելուց հետո | Միջոց՝ ձայնը | Կոդ՝ իսպաներեն | Իրավիճակ՝ բժշկի ընդունարանը',
    highlightCategory: 'general'
  },
  {
    id: 'p2-q7',
    block: 2,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Completa los elementos',
    partTitleHy: 'Մաս 2 — Լրացրո՛ւ տարրերը',
    number: 7,
    scenarioEs: 'En el colegio, un cartel dice: «Salida de emergencia.»',
    scenarioHy: 'Դպրոցում ցուցանակի վրա գրված է․ «Վթարային ելք»։',
    questionEs: 'Completa los seis elementos:',
    questionHy: 'Լրացրո՛ւ վեց տարրերը․',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'la institución / el colegio', answerHy: 'հաստատությունը / դպրոցի ղեկավարությունը' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'las personas que leen el cartel', answerHy: 'ցուցանակը կարդացող մարդիկ' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Salida de emergencia»', answerHy: '«Վթարային ելք»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'cartel / canal escrito', answerHy: 'ցուցանակ / գրավոր միջոց' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'el colegio / una situación de orientación o seguridad', answerHy: 'դպրոցը / անվտանգության և կողմնորոշման իրավիճակ' }
    ],
    officialAnswerEs: 'Emisor: la institución / el colegio | Receptor: las personas que leen el cartel | Mensaje: Salida de emergencia | Canal: cartel / canal escrito | Código: español | Contexto: el colegio / una situación de orientación o seguridad',
    officialAnswerHy: 'Հաղորդող՝ դպրոցը/հաստատությունը | Ընդունող՝ կարդացողները | Հաղորդագրություն՝ «Վթարային ելք» | Միջոց՝ ցուցանակը | Կոդ՝ իսպաներեն | Իրավիճակ՝ դպրոց/անվտանգություն',
    highlightCategory: 'general'
  },
  {
    id: 'p2-q8',
    block: 2,
    partNumber: 2,
    partTitleEs: 'Parte 2 — Completa los elementos',
    partTitleHy: 'Մաս 2 — Լրացրո՛ւ տարրերը',
    number: 8,
    scenarioEs: 'Laura llama a su padre y le dice: «El autobús llegará a las ocho.»',
    scenarioHy: 'Լաուրան զանգահարում է հորը և ասում․ «Ավտոբուսը կհասնի ժամը ութին»։',
    questionEs: 'Completa los seis elementos:',
    questionHy: 'Լրացրո՛ւ վեց տարրերը․',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'Laura', answerHy: 'Լաուրան' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'su padre', answerHy: 'հայրը' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«El autobús llegará a las ocho»', answerHy: '«Ավտոբուսը կհասնի ժամը ութին»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'teléfono / voz', answerHy: 'հեռախոս / ձայն' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'una llamada sobre la llegada del autobús', answerHy: 'հեռախոսազանգ ավտոբուսի ժամանման մասին' }
    ],
    officialAnswerEs: 'Emisor: Laura | Receptor: su padre | Mensaje: El autobús llegará a las ocho | Canal: teléfono / voz | Código: español | Contexto: una llamada sobre la llegada del autobús',
    officialAnswerHy: 'Հաղորդող՝ Լաուրան | Ընդունող՝ հայրը | Հաղորդագրություն՝ Ավտոբուսը կգա ութին | Միջոց՝ հեռախոս/ձայն | Կոդ՝ իսպաներեն | Իրավիճակ՝ հեռախոսազանգ',
    highlightCategory: 'general'
  },

  // Parte 3 — ¿Canal o código? (9-13)
  {
    id: 'p2-q9',
    block: 2,
    partNumber: 3,
    partTitleEs: 'Parte 3 — ¿Canal o código?',
    partTitleHy: 'Մաս 3 — Ալի՞ք, թե՞ կոդ',
    number: 9,
    questionEs: 'Español → ¿canal o código?',
    questionHy: 'Իսպաներեն → ալի՞ք, թե՞ կոդ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'b', textEs: 'Canal', textHy: 'Ալիք' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Código.',
    officialAnswerHy: 'Կոդ (նշանների համակարգ/լեզու)։',
    explanationEs: 'El español es una lengua (código lingüístico).',
    explanationHy: 'Իսպաներենը լեզու է (լեզվական կոդ)։',
    highlightCategory: 'código'
  },
  {
    id: 'p2-q10',
    block: 2,
    partNumber: 3,
    partTitleEs: 'Parte 3 — ¿Canal o código?',
    partTitleHy: 'Մաս 3 — Ալի՞ք, թե՞ կոդ',
    number: 10,
    questionEs: 'Teléfono → ¿canal o código?',
    questionHy: 'Հեռախոս → ալի՞ք, թե՞ կոդ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'b', textEs: 'Canal', textHy: 'Ալիք / հաղորդման միջոց' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'Canal.',
    officialAnswerHy: 'Ալիք / հաղորդման միջոց։',
    explanationEs: 'El teléfono es el medio físico/técnico de transmisión.',
    explanationHy: 'Հեռախոսը ֆիզիկական/տեխնիկական հաղորդման միջոցն է։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q11',
    block: 2,
    partNumber: 3,
    partTitleEs: 'Parte 3 — ¿Canal o código?',
    partTitleHy: 'Մաս 3 — Ալի՞ք, թե՞ կոդ',
    number: 11,
    questionEs: 'Lengua de signos → ¿canal o código?',
    questionHy: 'Ժեստերի լեզու → ալի՞ք, թե՞ կոդ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'b', textEs: 'Canal', textHy: 'Ալիք' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Código.',
    officialAnswerHy: 'Կոդ (նշանների համակարգ)։',
    explanationEs: 'Es un sistema organizado de signos gestuales.',
    explanationHy: 'Այն ժեստային նշանների կանոնավոր համակարգ է։',
    highlightCategory: 'código'
  },
  {
    id: 'p2-q12',
    block: 2,
    partNumber: 3,
    partTitleEs: 'Parte 3 — ¿Canal o código?',
    partTitleHy: 'Մաս 3 — Ալի՞ք, թե՞ կոդ',
    number: 12,
    questionEs: 'Una carta → ¿canal o código?',
    questionHy: 'Նամակ (թուղթ) → ալի՞ք, թե՞ կոդ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Código', textHy: 'Կոդ' },
      { key: 'b', textEs: 'Canal', textHy: 'Ալիք / կրիչ' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'Canal.',
    officialAnswerHy: 'Ալիք / կրիչ։',
    explanationEs: 'El papel de la carta es el soporte físico (canal escrito).',
    explanationHy: 'Նամակի թուղթը ֆիզիկական նյութական կրիչն է (գրավոր ալիք)։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q13',
    block: 2,
    partNumber: 3,
    partTitleEs: 'Parte 3 — ¿Canal o código?',
    partTitleHy: 'Մաս 3 — Ալի՞ք, թե՞ կոդ',
    number: 13,
    questionEs: 'Un dibujo utilizado para comunicar una idea → ¿puede funcionar como código?',
    questionHy: 'Գաղափար փոխանցելու համար օգտագործվող նկարը կարո՞ղ է ծառայել որպես կոդ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Sí', textHy: 'Այո' },
      { key: 'b', textEs: 'No', textHy: 'Ոչ' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Sí.',
    officialAnswerHy: 'Այո։ Նկարը կարող է կոդ լինել, եթե օգտագործվում է իմաստ փոխանցելու համար։',
    explanationEs: 'Los pictogramas, señales e iconos constituyen códigos no verbales.',
    explanationHy: 'Պիկտոգրամները, պատկերանշանները և սրբապատկերները ոչ վերբալ կոդեր են։',
    highlightCategory: 'código'
  },

  // Parte 4 — Encuentra el error (14-16)
  {
    id: 'p2-q14',
    block: 2,
    partNumber: 4,
    partTitleEs: 'Parte 4 — Encuentra el error',
    partTitleHy: 'Մաս 4 — Գտի՛ր սխալը',
    number: 14,
    scenarioEs: 'Ana habla con Pedro por teléfono en español.\nUn alumno responde:\n- Emisor: Ana\n- Receptor: Pedro\n- Canal: español\n- Código: teléfono',
    scenarioHy: 'Անան Պեդրոյի հետ հեռախոսով խոսում է իսպաներեն։\nԱշակերտը պատասխանում է․\n- Հաղորդող՝ Անա\n- Ընդունող՝ Պեդրո\n- Ալիք՝ իսպաներեն\n- Կոդ՝ հեռախոս',
    questionEs: '¿Qué está mal?',
    questionHy: 'Ի՞նչն է սխալ։',
    type: 'error_detection',
    officialAnswerEs: 'Canal y código están cambiados. Correcto: Canal: teléfono | Código: español.',
    officialAnswerHy: 'Ալիքն ու կոդը փոխված են տեղերով։ Ճիշտ է՝ Ալիք՝ հեռախոս | Կոդ՝ իսպաներեն։',
    explanationEs: 'El canal es el medio tecnológico (teléfono), y el código es el idioma (español).',
    explanationHy: 'Ալիքը հեռախոսն է, իսկ կոդը՝ իսպաներեն լեզուն։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q15',
    block: 2,
    partNumber: 4,
    partTitleEs: 'Parte 4 — Encuentra el error',
    partTitleHy: 'Մաս 4 — Գտի՛ր սխալը',
    number: 15,
    scenarioEs: 'Un profesor dice: «El examen empieza a las nueve.»\nUn alumno escribe: Mensaje: el profesor.',
    scenarioHy: 'Ուսուցիչն ասում է․ «Քննությունը սկսվում է ժամը իննին»։\nԱշակերտը գրում է․ Հաղորդագրություն՝ ուսուցիչը։',
    questionEs: '¿Es correcto? Corrige el error.',
    questionHy: 'Ճի՞շտ է։ Ուղղի՛ր սխալը։',
    type: 'error_detection',
    officialAnswerEs: 'No. El profesor es el emisor. El mensaje es: «El examen empieza a las nueve.»',
    officialAnswerHy: 'Ոչ։ Ուսուցիչը հաղորդողն է։ Հաղորդագրությունը՝ «Քննությունը սկսվում է ժամը իննին»։',
    explanationEs: 'El profesor es la persona que emite; las palabras pronunciadas son el mensaje.',
    explanationHy: 'Ուսուցիչը հաղորդող անձն է, իսկ նրա ասած խոսքերը՝ հաղորդագրությունը։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p2-q16',
    block: 2,
    partNumber: 4,
    partTitleEs: 'Parte 4 — Encuentra el error',
    partTitleHy: 'Մաս 4 — Գտի՛ր սխալը',
    number: 16,
    scenarioEs: 'Una señal de tráfico indica «STOP».\nUn alumno dice: Receptor: la señal.',
    scenarioHy: 'Ճանապարհային նշանը ցույց է տալիս «STOP»։\nԱշակերտն ասում է․ Ընդունող՝ նշանը։',
    questionEs: '¿Correcto? Corrige el error.',
    questionHy: 'Ճի՞շտ է։ Ուղղի՛ր սխալը։',
    type: 'error_detection',
    officialAnswerEs: 'No. Los receptores son los conductores que ven la señal.',
    officialAnswerHy: 'Ոչ։ Ընդունողները ճանապարհային նշանը տեսնող վարորդներն են։',
    explanationEs: 'La señal es el canal/soporte; el receptor humano es quien la percibe y acata.',
    explanationHy: 'Նշանը հաղորդման միջոցն է, իսկ ընդունողը՝ այն տեսնող և հասկացող վարորդը։',
    highlightCategory: 'receptor'
  },

  // Parte 5 — Situaciones tipo examen (17-20)
  {
    id: 'p2-q17',
    block: 2,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Situaciones tipo examen',
    partTitleHy: 'Մաս 5 — Քննության տիպի իրավիճակներ',
    number: 17,
    scenarioEs: 'Durante un partido, el árbitro pita y señala una falta.',
    scenarioHy: 'Խաղի ընթացքում մրցավարը սուլում է և մատնանշում խախտումը։',
    questionEs: '¿Cuál puede ser el mensaje?',
    questionHy: 'Ո՞րն է հաղորդագրությունը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Hay una falta', textHy: 'Խախտում կա / ֆոլ է' },
      { key: 'b', textEs: 'El árbitro', textHy: 'Մրցավարը' },
      { key: 'c', textEs: 'El silbato', textHy: 'Սուլիչը' },
      { key: 'd', textEs: 'El campo', textHy: 'Դաշտը' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Hay una falta',
    officialAnswerHy: 'ա) Խախտում կա',
    explanationEs: 'El mensaje comunicado a todos los jugadores es que se ha cometido una infracción.',
    explanationHy: 'Փոխանցվող տեղեկությունն այն է, որ խաղի կանոնները խախտվել են։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p2-q18',
    block: 2,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Situaciones tipo examen',
    partTitleHy: 'Մաս 5 — Քննության տիպի իրավիճակներ',
    number: 18,
    scenarioEs: 'En esa misma situación (el árbitro pita y señala falta):',
    scenarioHy: 'Նույն իրավիճակում (մրցավարը սուլում է և ցույց տալիս խախտումը)․',
    questionEs: '¿Cuál es el canal principal en esa situación?',
    questionHy: 'Ո՞րն է հիմնական միջոցը (ալիքը)։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'El fútbol', textHy: 'Ֆուտբոլը' },
      { key: 'b', textEs: 'El silbato y la señal gestual', textHy: 'Սուլիչի ձայնը և ժեստը' },
      { key: 'c', textEs: 'El árbitro', textHy: 'Մրցավարը' },
      { key: 'd', textEs: 'El jugador', textHy: 'Խաղացողը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) El silbato y la señal gestual',
    officialAnswerHy: 'բ) Սուլիչը և ժեստային ազդանշանը',
    explanationEs: 'El sonido del silbato (auditivo) y el brazo levantado (visual) conducen el mensaje.',
    explanationHy: 'Սուլիչի ձայնն ու ձեռքի շարժումը հաղորդում են ազդանշանը։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q19',
    block: 2,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Situaciones tipo examen',
    partTitleHy: 'Մաս 5 — Քննության տիպի իրավիճակներ',
    number: 19,
    scenarioEs: 'En esa misma situación:',
    scenarioHy: 'Նույն իրավիճակում․',
    questionEs: '¿Cuál es el código?',
    questionHy: 'Ո՞րն է կոդը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Las señales arbitrales conocidas por los jugadores', textHy: 'Մրցավարական նշանների համակարգը՝ հայտնի խաղացողներին' },
      { key: 'b', textEs: 'El campo', textHy: 'Դաշտը' },
      { key: 'c', textEs: 'El árbitro', textHy: 'Մրցավարը' },
      { key: 'd', textEs: 'La falta', textHy: 'Խախտումը' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Las señales arbitrales conocidas por los jugadores',
    officialAnswerHy: 'ա) Մրցավարական նշանների համակարգը',
    explanationEs: 'El reglamento y los códigos gestuales convenidos forman el sistema de signos.',
    explanationHy: 'Մրցավարական կանոններն ու ժեստերը կազմում են նշանների պայմանական համակարգը։',
    highlightCategory: 'código'
  },
  {
    id: 'p2-q20',
    block: 2,
    partNumber: 5,
    partTitleEs: 'Parte 5 — Situaciones tipo examen',
    partTitleHy: 'Մաս 5 — Քննության տիպի իրավիճակներ',
    number: 20,
    scenarioEs: 'En el recreo, Marta dice a Lucía: «Te espero junto a la puerta principal.»',
    scenarioHy: 'Դասամիջոցին Մարթան ասում է Լուկիային․ «Քեզ կսպասեմ գլխավոր դռան մոտ»։',
    questionEs: '¿Quién es el receptor?',
    questionHy: 'Ո՞վ է ընդունողը։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Marta', textHy: 'Մարթան' },
      { key: 'b', textEs: 'Lucía', textHy: 'Լուկիան' },
      { key: 'c', textEs: 'La puerta', textHy: 'Դուռը' },
      { key: 'd', textEs: 'El recreo', textHy: 'Դասամիջոցը' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Lucía',
    officialAnswerHy: 'բ) Լուկիան',
    explanationEs: 'Lucía es la destinataria que recibe y escucha el mensaje.',
    explanationHy: 'Լուկիան այն անձն է, ում ուղղված է խոսքը։',
    highlightCategory: 'receptor'
  },

  // Parte 6 — Texto para analizar (21-26)
  {
    id: 'p2-q21',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 21,
    scenarioEs: 'Texto: Al terminar la clase, el profesor dice: —Mañana traeréis el libro de Ciencias...',
    scenarioHy: 'Տեքստ․ Դասի վերջում ուսուցիչն ասում է․ — Վաղը բերելու եք բնագիտության գիրքը...',
    questionEs: '¿Quién es el emisor del primer mensaje?',
    questionHy: 'Ո՞վ է առաջին հաղորդագրության հաղորդողը։',
    type: 'open',
    officialAnswerEs: 'El profesor.',
    officialAnswerHy: 'Ուսուցիչը։',
    explanationEs: 'El profesor inicia la comunicación con la indicación a la clase.',
    explanationHy: 'Ուսուցիչն է առաջին հրահանգը տվողը։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p2-q22',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 22,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Quiénes son los receptores?',
    questionHy: 'Ովքե՞ր են ընդունողները։',
    type: 'open',
    officialAnswerEs: 'Los alumnos.',
    officialAnswerHy: 'Աշակերտները։',
    explanationEs: 'Toda la clase de alumnos recibe la indicación del profesor.',
    explanationHy: 'Դասարանի բոլոր աշակերտները ստանում են հանձնարարությունը։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p2-q23',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 23,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el mensaje?',
    questionHy: 'Ո՞րն է հաղորդագրությունը։',
    type: 'open',
    officialAnswerEs: 'Mañana traeréis el libro de Ciencias.',
    officialAnswerHy: 'Վաղը բերելու եք բնագիտության գիրքը։',
    explanationEs: 'La obligación de traer el libro de Ciencias mañana.',
    explanationHy: 'Բուն հանձնարարականը՝ վաղը գիրքը բերելու մասին։',
    highlightCategory: 'mensaje'
  },
  {
    id: 'p2-q24',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 24,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el canal cuando el profesor habla?',
    questionHy: 'Ո՞րն է հաղորդման միջոցը, երբ ուսուցիչը խոսում է։',
    type: 'open',
    officialAnswerEs: 'La voz / canal oral.',
    officialAnswerHy: 'Ձայնը / բանավոր միջոցը (օդային ալիքները)։',
    explanationEs: 'La emisión sonora transmitida por el aire.',
    explanationHy: 'Օդի միջոցով տարածվող ձայնային ալիքները։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q25',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 25,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cuál es el canal cuando escribe en la pizarra?',
    questionHy: 'Ո՞րն է հաղորդման միջոցը, երբ նա գրում է գրատախտակին։',
    type: 'open',
    officialAnswerEs: 'La pizarra / canal escrito.',
    officialAnswerHy: 'Գրատախտակը / գրավոր միջոցը։',
    explanationEs: 'La superficie de la pizarra sirve de soporte físico para el texto.',
    explanationHy: 'Գրատախտակի մակերեսը ծառայում է որպես գրավոր նշանների կրիչ։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q26',
    block: 2,
    partNumber: 6,
    partTitleEs: 'Parte 6 — Texto para analizar',
    partTitleHy: 'Մաս 6 — Վերլուծի՛ր տեքստը',
    number: 26,
    scenarioEs: 'En el mismo texto:',
    scenarioHy: 'Նույն տեքստում․',
    questionEs: '¿Cambia el mensaje cuando cambia el canal?',
    questionHy: 'Հաղորդագրությունը փոխվո՞ւմ է, եթե ալիքը փոխվում է։',
    type: 'open',
    officialAnswerEs: 'No necesariamente. El mensaje puede ser el mismo y cambiar solamente el canal.',
    officialAnswerHy: 'Ոչ պարտադիր։ Հաղորդագրությունը կարող է մնալ նույնը, իսկ փոխվի միայն ալիքը։',
    explanationEs: 'El contenido informativo permanece idéntico aunque cambie el soporte oral a escrito.',
    explanationHy: 'Բովանդակությունը մնում է նույնը, նույնիսկ եթե բանավորից անցնում են գրավորի։',
    highlightCategory: 'canal'
  },

  // Parte 7 — Preguntas con más razonamiento (27-30)
  {
    id: 'p2-q27',
    block: 2,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Preguntas con más razonamiento',
    partTitleHy: 'Մաս 7 — Ավելի մտածելու հարցեր',
    number: 27,
    scenarioEs: 'Un turista pregunta algo en español, pero la otra persona solo entiende alemán.',
    scenarioHy: 'Զբոսաշրջիկը հարցնում է իսպաներեն, բայց մյուս մարդը միայն գերմաներեն է հասկանում։',
    questionEs: '¿Qué problema hay?',
    questionHy: 'Ի՞նչ խնդիր կա։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Falla el emisor', textHy: 'Հաղորդողի մեջ է խնդիրը' },
      { key: 'b', textEs: 'No comparten el mismo código', textHy: 'Նրանք չունեն ընդհանուր կոդ (լեզու)' },
      { key: 'c', textEs: 'No existe mensaje', textHy: 'Հաղորդագրություն չկա' },
      { key: 'd', textEs: 'No hay receptor', textHy: 'Ընդունող չկա' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) No comparten el mismo código',
    officialAnswerHy: 'բ) Նրանք նույն կոդը չեն հասկանում (ընդհանուր լեզու չունեն)։',
    explanationEs: 'Para que la comunicación funcione, emisor y receptor deben compartir el código.',
    explanationHy: 'Հաղորդակցության կայացման համար հաղորդողն ու ընդունողը պետք է իմանան նույն կոդը։',
    highlightCategory: 'código'
  },
  {
    id: 'p2-q28',
    block: 2,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Preguntas con más razonamiento',
    partTitleHy: 'Մաս 7 — Ավելի մտածելու հարցեր',
    number: 28,
    scenarioEs: 'Si hay mucho ruido ambiental y el receptor no oye el mensaje...',
    scenarioHy: 'Եթե շուրջը շատ աղմուկ կա և ընդունողը չի լսում հաղորդագրությունը․․․',
    questionEs: '¿Qué elemento está afectado principalmente?',
    questionHy: 'Ո՞ր տարրն է հիմնականում տուժում (խաթարվում)։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Canal', textHy: 'Ալիքը / հաղորդման միջոցը' },
      { key: 'b', textEs: 'Emisor', textHy: 'Հաղորդողը' },
      { key: 'c', textEs: 'Código', textHy: 'Կոդը' },
      { key: 'd', textEs: 'Contexto', textHy: 'Համատեքստը' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'a) Canal',
    officialAnswerHy: 'ա) Ալիքը / հաղորդման միջոցը',
    explanationEs: 'El ruido interfiere en el canal físico dificultando el paso de las ondas.',
    explanationHy: 'Աղմուկը ֆիզիկական խոչընդոտ է հենց հաղորդման ալիքում (ruido en el canal)։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q29',
    block: 2,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Preguntas con más razonamiento',
    partTitleHy: 'Մաս 7 — Ավելի մտածելու հարցեր',
    number: 29,
    scenarioEs: 'En una conversación, Ana habla y Pedro escucha. Después Pedro responde.',
    scenarioHy: 'Զրույցում Անան խոսում է, իսկ Պեդրոն լսում։ Հետո Պեդրոն պատասխանում է։',
    questionEs: '¿Qué ocurre?',
    questionHy: 'Ի՞նչ է տեղի ունենում։',
    type: 'mcq',
    options: [
      { key: 'a', textEs: 'Ana siempre sigue siendo emisora', textHy: 'Անան միշտ մնում է հաղորդող' },
      { key: 'b', textEs: 'Pedro se convierte en emisor', textHy: 'Պեդրոն դառնում է հաղորդող' },
      { key: 'c', textEs: 'No cambia nada', textHy: 'Ոչինչ չի փոխվում' },
      { key: 'd', textEs: 'Desaparece el receptor', textHy: 'Ընդունողը վերանում է' }
    ],
    correctKey: 'b',
    officialAnswerEs: 'b) Pedro se convierte en emisor',
    officialAnswerHy: 'բ) Պեդրոն դառնում է հաղորդող։',
    explanationEs: 'Al responder, Pedro asume el rol de emisor y Ana pasa a ser receptora.',
    explanationHy: 'Երբ Պեդրոն պատասխանում է, նա ստանձնում է հաղորդողի դերը, իսկ Անան՝ ընդունողի։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p2-q30',
    block: 2,
    partNumber: 7,
    partTitleEs: 'Parte 7 — Preguntas con más razonamiento',
    partTitleHy: 'Մաս 7 — Ավելի մտածելու հարցեր',
    number: 30,
    scenarioEs: 'Reflexión general:',
    scenarioHy: 'Ընդհանուր եզրակացություն․',
    questionEs: '¿Puede un mismo mensaje tener distintos canales?',
    questionHy: 'Կարո՞ղ է նույն հաղորդագրությունն ունենալ տարբեր ալիքներ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Sí', textHy: 'Այո' },
      { key: 'b', textEs: 'No', textHy: 'Ոչ' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Sí. Ejemplo: «Mañana hay examen» puede decirse oralmente, escribirse en la pizarra o enviarse por mensaje.',
    officialAnswerHy: 'Այո։ Օրինակ՝ «Վաղը քննություն կա» կարելի է ասել բանավոր, գրել գրատախտակին կամ ուղարկել հաղորդագրությամբ։',
    explanationEs: 'El mensaje es la información; el canal es el vehículo elegido para emitirla.',
    explanationHy: 'Նույն հաղորդագրությունը կարելի է փոխանցել տարբեր ալիքներով։',
    highlightCategory: 'canal'
  },

  // Parte 8 — Responde sin opciones (31-32)
  {
    id: 'p2-q31',
    block: 2,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Responde sin opciones',
    partTitleHy: 'Մաս 8 — Պատասխանի՛ր առանց տարբերակների',
    number: 31,
    scenarioEs: 'Un chico manda un audio a su amigo diciendo: «Nos vemos en el parque a las cinco.»',
    scenarioHy: 'Տղան ձայնային հաղորդագրություն է ուղարկում ընկերոջը․ «Կհանդիպենք պուրակում ժամը հինգին»։',
    questionEs: 'Identifica tú solo los seis elementos:',
    questionHy: 'Ինքնուրույն որոշի՛ր վեց տարրերը․',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'el chico', answerHy: 'տղան' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'su amigo', answerHy: 'ընկերը' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Nos vemos en el parque a las cinco»', answerHy: '«Կհանդիպենք պուրակում ժամը հինգին»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'audio / teléfono', answerHy: 'աուդիո ձայնագրություն / հեռախոս' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'español', answerHy: 'իսպաներեն' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'dos amigos organizando un encuentro', answerHy: 'երկու ընկերների հանդիպման պլանավորում' }
    ],
    officialAnswerEs: 'Emisor: el chico | Receptor: su amigo | Mensaje: Nos vemos en el parque a las cinco | Canal: audio / teléfono | Código: español | Contexto: dos amigos organizando un encuentro',
    officialAnswerHy: 'Հաղորդող՝ տղան | Ընդունող՝ ընկերը | Հաղորդագրություն՝ Կհանդիպենք պուրակում հինգին | Միջոց՝ աուդիո/հեռախոս | Կոդ՝ իսպաներեն | Իրավիճակ՝ ընկերների պայմանավորվածություն',
    highlightCategory: 'general'
  },
  {
    id: 'p2-q32',
    block: 2,
    partNumber: 8,
    partTitleEs: 'Parte 8 — Responde sin opciones',
    partTitleHy: 'Մաս 8 — Պատասխանի՛ր առանց տարբերակների',
    number: 32,
    scenarioEs: 'Una profesora levanta un dedo delante de los labios para pedir silencio.',
    scenarioHy: 'Ուսուցչուհին մատը դնում է շուրթերին՝ լռություն խնդրելու համար։',
    questionEs: 'Identifica los seis elementos:',
    questionHy: 'Որոշի՛ր վեց տարրերը․',
    type: 'breakdown',
    breakdown: [
      { labelEs: 'Emisor', labelHy: 'Հաղորդող', answerEs: 'la profesora', answerHy: 'ուսուցչուհին' },
      { labelEs: 'Receptor', labelHy: 'Ընդունող', answerEs: 'los alumnos', answerHy: 'աշակերտները' },
      { labelEs: 'Mensaje', labelHy: 'Հաղորդագրություն', answerEs: '«Guardad silencio» / «Haced silencio»', answerHy: '«Լռություն պահպանեք»' },
      { labelEs: 'Canal', labelHy: 'Հաղորդման միջոց', answerEs: 'gesto / canal visual (la vista)', answerHy: 'ժեստ / տեսողական ալիք (տեսողություն)' },
      { labelEs: 'Código', labelHy: 'Կոդ', answerEs: 'gestual (no verbal)', answerHy: 'ժեստային (ոչ վերբալ)' },
      { labelEs: 'Contexto', labelHy: 'Իրավիճակ', answerEs: 'una clase en el colegio', answerHy: 'դասարանը / դասը' }
    ],
    officialAnswerEs: 'Emisor: la profesora | Receptor: los alumnos | Mensaje: Guardad silencio | Canal: gesto / canal visual | Código: gestual | Contexto: una clase',
    officialAnswerHy: 'Հաղորդող՝ ուսուցչուհին | Ընդունող՝ աշակերտները | Հաղորդագրություն՝ Լռություն պահպանեք | Միջոց՝ ժեստ/տեսողական | Կոդ՝ ժեստային | Իրավիճակ՝ դասը',
    highlightCategory: 'general'
  },

  // Parte 9 — Preguntas cortas para examen oral (33-37)
  {
    id: 'p2-q33',
    block: 2,
    partNumber: 9,
    partTitleEs: 'Parte 9 — Preguntas cortas para examen oral',
    partTitleHy: 'Մաս 9 — Կարճ հարցեր բանավոր քննության համար',
    number: 33,
    questionEs: '¿Qué diferencia hay entre emisor y receptor?',
    questionHy: 'Ի՞նչ տարբերություն կա հաղորդողի և ընդունողի միջև։',
    type: 'open',
    officialAnswerEs: 'El emisor envía el mensaje y el receptor lo recibe.',
    officialAnswerHy: 'Հաղորդողը ուղարկում է հաղորդագրությունը, իսկ ընդունողը ստանում է այն։',
    explanationEs: 'El emisor codifica y emite; el receptor percibe y descodifica.',
    explanationHy: 'Հաղորդողը ստեղծում և ուղարկում է հաղորդագրությունը, իսկ ընդունողը ստանում և ընկալում է։',
    highlightCategory: 'emisor'
  },
  {
    id: 'p2-q34',
    block: 2,
    partNumber: 9,
    partTitleEs: 'Parte 9 — Preguntas cortas para examen oral',
    partTitleHy: 'Մաս 9 — Կարճ հարցեր բանավոր քննության համար',
    number: 34,
    questionEs: '¿Qué diferencia hay entre canal y código?',
    questionHy: 'Ի՞նչ տարբերություն կա ալիքի և կոդի միջև։',
    type: 'open',
    officialAnswerEs: 'El canal es el medio por el que viaja el mensaje; el código es el sistema de signos usado para construirlo.',
    officialAnswerHy: 'Ալիքը այն միջոցն է, որով հաղորդագրությունը փոխանցվում է, իսկ կոդը՝ օգտագործվող նշանների համակարգը։',
    explanationEs: 'Canal = soporte físico (aire, cable, papel). Código = lenguaje/normas (español, señales).',
    explanationHy: 'Ալիք = ֆիզիկական հիմք (օդ, հեռախոս, թուղթ): Կոդ = լեզու կամ նշանների համակարգ։',
    highlightCategory: 'canal'
  },
  {
    id: 'p2-q35',
    block: 2,
    partNumber: 9,
    partTitleEs: 'Parte 9 — Preguntas cortas para examen oral',
    partTitleHy: 'Մաս 9 — Կարճ հարցեր բանավոր քննության համար',
    number: 35,
    questionEs: '¿Qué es el contexto?',
    questionHy: 'Ի՞նչ է համատեքստը / իրավիճակը։',
    type: 'open',
    officialAnswerEs: 'Es la situación en la que se produce la comunicación.',
    officialAnswerHy: 'Դա այն իրավիճակն է, որտեղ տեղի է ունենում հաղորդակցությունը։',
    explanationEs: 'Incluye el lugar, el momento y la relación entre los participantes.',
    explanationHy: 'Ներառում է վայրը, ժամանակը և մասնակիցների միջև փոխհարաբերությունները։',
    highlightCategory: 'contexto'
  },
  {
    id: 'p2-q36',
    block: 2,
    partNumber: 9,
    partTitleEs: 'Parte 9 — Preguntas cortas para examen oral',
    partTitleHy: 'Մաս 9 — Կարճ հարցեր բանավոր քննության համար',
    number: 36,
    questionEs: '¿Puede haber varios receptores?',
    questionHy: 'Կարո՞ղ են լինել մի քանի ընդունողներ։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Sí', textHy: 'Այո' },
      { key: 'b', textEs: 'No', textHy: 'Ոչ' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Sí.',
    officialAnswerHy: 'Այո, կարող են լինել մի քանի ընդունողներ (օրինակ՝ դասարանի աշակերտները, հեռուստադիտողները)։',
    explanationEs: 'Un mensaje puede dirigirse a una colectividad (ej. una clase, el público).',
    explanationHy: 'Հաղորդագրությունը կարող է ուղղված լինել միաժամանակ բազմաթիվ մարդկանց։',
    highlightCategory: 'receptor'
  },
  {
    id: 'p2-q37',
    block: 2,
    partNumber: 9,
    partTitleEs: 'Parte 9 — Preguntas cortas para examen oral',
    partTitleHy: 'Մաս 9 — Կարճ հարցեր բանավոր քննության համար',
    number: 37,
    questionEs: '¿Puede un receptor convertirse en emisor?',
    questionHy: 'Կարո՞ղ է արդյոք ընդունողը դառնալ հաղորդող։',
    type: 'comparison',
    options: [
      { key: 'a', textEs: 'Sí, especialmente en una conversación', textHy: 'Այո, հատկապես զրույցի ընթացքում' },
      { key: 'b', textEs: 'No, nunca', textHy: 'Ոչ, երբեք' }
    ],
    correctKey: 'a',
    officialAnswerEs: 'Sí, especialmente en una conversación.',
    officialAnswerHy: 'Այո, հատկապես զրույցի ընթացքում։',
    explanationEs: 'La comunicación humana es bidireccional; los roles se alternan constantemente.',
    explanationHy: 'Մարդկային հաղորդակցությունը երկկողմանի է, դերերը շարունակաբար փոխվում են։',
    highlightCategory: 'emisor'
  }
];
